#!/usr/bin/env sh

# Set menu bar opacity to 0 (invisible)
yabai -m config menubar_opacity 0.0

# yabai -m window_shadow on
# yabai -m active_window_opacity 1.0
# yabai -m normal_window_opacity 0.90

# Padding
yabai -m config top_padding 20
yabai -m config bottom_padding 10
yabai -m config right_padding 10
yabai -m config left_padding 10
yabai -m config window_gap 10

# mouse settings
# yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Finder$" manage=off

# Stuff that needs to happen idk why
yabai -m config layout bsp
yabai -m config window_placement second_child
